"""
Generate train_ours.txt / val_ours.txt / test_ours.txt for GANav's RUGD
data pipeline, based on whatever sample frames/annotations are actually
present on disk.

Safe by design:
- Never touches RUGD_annotations/ or RUGD_frames-with-annotations/, only reads them.
- Skips files already generated by rugd_relabel6_new.py (*_orig.png, *_group6new.png)
  so re-running the relabel script later doesn't pick up its own outputs as raw data.
- Only includes a frame if BOTH the annotation PNG and the matching raw image exist,
  since a mismatch there is a common cause of crashes deep in training.
- Backs up any existing train_ours.txt/val_ours.txt/test_ours.txt to .bak before
  overwriting, so you never lose a manually-curated split by accident.

Usage:
    python generate_rugd_splits.py
    python generate_rugd_splits.py --val-ratio 0.15 --test-ratio 0.15 --seed 42
"""

import argparse
import os
import os.path as osp
import random
import shutil

RUGD_DIR = "./data/rugd/"
ANNOTATION_FOLDER = "RUGD_annotations/"
FRAMES_FOLDER = "RUGD_frames-with-annotations/"

# outputs produced by rugd_relabel6_new.py -- never treat these as raw annotations
GENERATED_SUFFIXES = ("_orig.png", "_group6new.png", "_group6.png")

# extensions to look for on the raw-frame side (RUGD is normally .png, but
# checking a couple of common alternates costs nothing and avoids silent misses)
FRAME_EXTENSIONS = (".png", ".jpg", ".jpeg")


def is_generated_file(filename):
    return any(filename.endswith(suffix) for suffix in GENERATED_SUFFIXES)


def find_matching_frame(seq_dir_frames, stem):
    for ext in FRAME_EXTENSIONS:
        candidate = osp.join(seq_dir_frames, stem + ext)
        if osp.isfile(candidate):
            return True
    return False


def collect_pairs_from_dir(seq_ann_dir, seq_frames_dir, prefix=""):
    """Collect (rel_path, matched) pairs for one directory of annotation PNGs."""
    samples = []
    skipped_no_frame = []
    skipped_generated = 0

    for fname in sorted(os.listdir(seq_ann_dir)):
        if not fname.lower().endswith(".png"):
            continue
        if is_generated_file(fname):
            skipped_generated += 1
            continue

        stem = fname[:-4]  # strip ".png"
        rel_path = f"{prefix}{stem}" if prefix else stem

        if find_matching_frame(seq_frames_dir, stem):
            samples.append(rel_path)
        else:
            skipped_no_frame.append(rel_path)

    return samples, skipped_no_frame, skipped_generated


def collect_samples(rugd_dir):
    ann_root = osp.join(rugd_dir, ANNOTATION_FOLDER)
    frames_root = osp.join(rugd_dir, FRAMES_FOLDER)

    if not osp.isdir(ann_root):
        raise FileNotFoundError(f"Annotation folder not found: {ann_root}")
    if not osp.isdir(frames_root):
        raise FileNotFoundError(f"Frames folder not found: {frames_root}")

    samples = []
    skipped_no_frame = []
    skipped_generated = 0

    # detect layout: if RUGD_annotations contains .png files directly, it's flat.
    # if it contains subdirectories, treat those as per-sequence folders.
    entries = sorted(os.listdir(ann_root))
    has_flat_pngs = any(
        e.lower().endswith(".png") and osp.isfile(osp.join(ann_root, e)) for e in entries
    )
    has_subdirs = any(osp.isdir(osp.join(ann_root, e)) for e in entries)

    if has_flat_pngs and not has_subdirs:
        print("Detected flat layout (no per-sequence subfolders).")
        s, skip_nf, skip_gen = collect_pairs_from_dir(ann_root, frames_root, prefix="")
        samples.extend(s)
        skipped_no_frame.extend(skip_nf)
        skipped_generated += skip_gen

    elif has_subdirs:
        print("Detected nested layout (per-sequence subfolders).")
        for seq_name in entries:
            seq_ann_dir = osp.join(ann_root, seq_name)
            if not osp.isdir(seq_ann_dir):
                continue

            seq_frames_dir = osp.join(frames_root, seq_name)
            if not osp.isdir(seq_frames_dir):
                print(f"  [skip] no matching frames sequence folder for '{seq_name}', skipping entire sequence")
                continue

            s, skip_nf, skip_gen = collect_pairs_from_dir(
                seq_ann_dir, seq_frames_dir, prefix=f"{seq_name}/"
            )
            samples.extend(s)
            skipped_no_frame.extend(skip_nf)
            skipped_generated += skip_gen

    else:
        print("RUGD_annotations/ appears to be empty.")

    print(f"Found {len(samples)} usable annotation/frame pairs.")
    if skipped_generated:
        print(f"Skipped {skipped_generated} already-generated relabel outputs.")
    if skipped_no_frame:
        print(f"Skipped {len(skipped_no_frame)} annotations with no matching raw frame:")
        for s in skipped_no_frame[:10]:
            print(f"    {s}")
        if len(skipped_no_frame) > 10:
            print(f"    ...and {len(skipped_no_frame) - 10} more")

    return samples


def split_samples(samples, val_ratio, test_ratio, seed):
    rng = random.Random(seed)
    shuffled = samples[:]
    rng.shuffle(shuffled)

    n = len(shuffled)
    n_val = int(n * val_ratio)
    n_test = int(n * test_ratio)

    val = shuffled[:n_val]
    test = shuffled[n_val:n_val + n_test]
    train = shuffled[n_val + n_test:]

    return train, val, test


def backup_if_exists(path):
    if osp.isfile(path):
        backup_path = path + ".bak"
        shutil.copy2(path, backup_path)
        print(f"  backed up existing {path} -> {backup_path}")


def write_split(path, items):
    backup_if_exists(path)
    with open(path, "w") as f:
        for item in items:
            f.write(item + "\n")
    print(f"  wrote {len(items)} lines to {path}")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--val-ratio", type=float, default=0.15)
    parser.add_argument("--test-ratio", type=float, default=0.15)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--rugd-dir", type=str, default=RUGD_DIR)
    args = parser.parse_args()

    print(f"Scanning {args.rugd_dir} ...")
    samples = collect_samples(args.rugd_dir)

    if not samples:
        print("No usable samples found -- nothing written. Check your folder structure.")
        return

    train, val, test = split_samples(samples, args.val_ratio, args.test_ratio, args.seed)

    print("\nWriting split files:")
    write_split(osp.join(args.rugd_dir, "train_ours.txt"), train)
    write_split(osp.join(args.rugd_dir, "val_ours.txt"), val)
    write_split(osp.join(args.rugd_dir, "test_ours.txt"), test)

    print(f"\nDone. train={len(train)} val={len(val)} test={len(test)}")


if __name__ == "__main__":
    main()